//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClient.APLService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="User")]
    [System.SerializableAttribute()]
    public class UserList : System.Collections.Generic.List<WpfClient.APLService.User> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class User : WpfClient.APLService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BIRTHDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClient.APLService.Group FAVORITEGROUPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClient.APLService.GuessList GuessesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ISADMINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BIRTHDATE {
            get {
                return this.BIRTHDATEField;
            }
            set {
                if ((this.BIRTHDATEField.Equals(value) != true)) {
                    this.BIRTHDATEField = value;
                    this.RaisePropertyChanged("BIRTHDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL {
            get {
                return this.EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILField, value) != true)) {
                    this.EMAILField = value;
                    this.RaisePropertyChanged("EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClient.APLService.Group FAVORITEGROUP {
            get {
                return this.FAVORITEGROUPField;
            }
            set {
                if ((object.ReferenceEquals(this.FAVORITEGROUPField, value) != true)) {
                    this.FAVORITEGROUPField = value;
                    this.RaisePropertyChanged("FAVORITEGROUP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClient.APLService.GuessList Guesses {
            get {
                return this.GuessesField;
            }
            set {
                if ((object.ReferenceEquals(this.GuessesField, value) != true)) {
                    this.GuessesField = value;
                    this.RaisePropertyChanged("Guesses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ISADMIN {
            get {
                return this.ISADMINField;
            }
            set {
                if ((this.ISADMINField.Equals(value) != true)) {
                    this.ISADMINField = value;
                    this.RaisePropertyChanged("ISADMIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassWord {
            get {
                return this.PassWordField;
            }
            set {
                if ((object.ReferenceEquals(this.PassWordField, value) != true)) {
                    this.PassWordField = value;
                    this.RaisePropertyChanged("PassWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfClient.APLService.Group))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfClient.APLService.Guess))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfClient.APLService.Game))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfClient.APLService.Player))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfClient.APLService.User))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Group : WpfClient.APLService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupShortcutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupShortcut {
            get {
                return this.GroupShortcutField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupShortcutField, value) != true)) {
                    this.GroupShortcutField = value;
                    this.RaisePropertyChanged("GroupShortcut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Guess", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Guess : WpfClient.APLService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClient.APLService.Game GAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ISCORRECTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ISDRAWField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClient.APLService.Group TEAMGUESSEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClient.APLService.User USERField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClient.APLService.Game GAME {
            get {
                return this.GAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.GAMEField, value) != true)) {
                    this.GAMEField = value;
                    this.RaisePropertyChanged("GAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ISCORRECT {
            get {
                return this.ISCORRECTField;
            }
            set {
                if ((this.ISCORRECTField.Equals(value) != true)) {
                    this.ISCORRECTField = value;
                    this.RaisePropertyChanged("ISCORRECT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ISDRAW {
            get {
                return this.ISDRAWField;
            }
            set {
                if ((this.ISDRAWField.Equals(value) != true)) {
                    this.ISDRAWField = value;
                    this.RaisePropertyChanged("ISDRAW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClient.APLService.Group TEAMGUESSED {
            get {
                return this.TEAMGUESSEDField;
            }
            set {
                if ((object.ReferenceEquals(this.TEAMGUESSEDField, value) != true)) {
                    this.TEAMGUESSEDField = value;
                    this.RaisePropertyChanged("TEAMGUESSED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClient.APLService.User USER {
            get {
                return this.USERField;
            }
            set {
                if ((object.ReferenceEquals(this.USERField, value) != true)) {
                    this.USERField = value;
                    this.RaisePropertyChanged("USER");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Game", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Game : WpfClient.APLService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AWAYSCOREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClient.APLService.Group AWAYTEAMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HOMESCOREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClient.APLService.Group HOMETEAMField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AWAYSCORE {
            get {
                return this.AWAYSCOREField;
            }
            set {
                if ((this.AWAYSCOREField.Equals(value) != true)) {
                    this.AWAYSCOREField = value;
                    this.RaisePropertyChanged("AWAYSCORE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClient.APLService.Group AWAYTEAM {
            get {
                return this.AWAYTEAMField;
            }
            set {
                if ((object.ReferenceEquals(this.AWAYTEAMField, value) != true)) {
                    this.AWAYTEAMField = value;
                    this.RaisePropertyChanged("AWAYTEAM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HOMESCORE {
            get {
                return this.HOMESCOREField;
            }
            set {
                if ((this.HOMESCOREField.Equals(value) != true)) {
                    this.HOMESCOREField = value;
                    this.RaisePropertyChanged("HOMESCORE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClient.APLService.Group HOMETEAM {
            get {
                return this.HOMETEAMField;
            }
            set {
                if ((object.ReferenceEquals(this.HOMETEAMField, value) != true)) {
                    this.HOMETEAMField = value;
                    this.RaisePropertyChanged("HOMETEAM");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Player : WpfClient.APLService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCaptainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClient.APLService.Group PlayerGroupField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCaptain {
            get {
                return this.IsCaptainField;
            }
            set {
                if ((this.IsCaptainField.Equals(value) != true)) {
                    this.IsCaptainField = value;
                    this.RaisePropertyChanged("IsCaptain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClient.APLService.Group PlayerGroup {
            get {
                return this.PlayerGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerGroupField, value) != true)) {
                    this.PlayerGroupField = value;
                    this.RaisePropertyChanged("PlayerGroup");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="GuessList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Guess")]
    [System.SerializableAttribute()]
    public class GuessList : System.Collections.Generic.List<WpfClient.APLService.Guess> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="GameList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Game")]
    [System.SerializableAttribute()]
    public class GameList : System.Collections.Generic.List<WpfClient.APLService.Game> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="GroupList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Group")]
    [System.SerializableAttribute()]
    public class GroupList : System.Collections.Generic.List<WpfClient.APLService.Group> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PlayerList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Player")]
    [System.SerializableAttribute()]
    public class PlayerList : System.Collections.Generic.List<WpfClient.APLService.Player> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APLService.IServiceBase")]
    public interface IServiceBase {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllUsers", ReplyAction="http://tempuri.org/IServiceBase/GetAllUsersResponse")]
        WpfClient.APLService.UserList GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllUsers", ReplyAction="http://tempuri.org/IServiceBase/GetAllUsersResponse")]
        System.Threading.Tasks.Task<WpfClient.APLService.UserList> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllGames", ReplyAction="http://tempuri.org/IServiceBase/GetAllGamesResponse")]
        WpfClient.APLService.GameList GetAllGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllGames", ReplyAction="http://tempuri.org/IServiceBase/GetAllGamesResponse")]
        System.Threading.Tasks.Task<WpfClient.APLService.GameList> GetAllGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllGroups", ReplyAction="http://tempuri.org/IServiceBase/GetAllGroupsResponse")]
        WpfClient.APLService.GroupList GetAllGroups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllGroups", ReplyAction="http://tempuri.org/IServiceBase/GetAllGroupsResponse")]
        System.Threading.Tasks.Task<WpfClient.APLService.GroupList> GetAllGroupsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllGuesses", ReplyAction="http://tempuri.org/IServiceBase/GetAllGuessesResponse")]
        WpfClient.APLService.GuessList GetAllGuesses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllGuesses", ReplyAction="http://tempuri.org/IServiceBase/GetAllGuessesResponse")]
        System.Threading.Tasks.Task<WpfClient.APLService.GuessList> GetAllGuessesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllPlayers", ReplyAction="http://tempuri.org/IServiceBase/GetAllPlayersResponse")]
        WpfClient.APLService.PlayerList GetAllPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllPlayers", ReplyAction="http://tempuri.org/IServiceBase/GetAllPlayersResponse")]
        System.Threading.Tasks.Task<WpfClient.APLService.PlayerList> GetAllPlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertUser", ReplyAction="http://tempuri.org/IServiceBase/InsertUserResponse")]
        int InsertUser(WpfClient.APLService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertUser", ReplyAction="http://tempuri.org/IServiceBase/InsertUserResponse")]
        System.Threading.Tasks.Task<int> InsertUserAsync(WpfClient.APLService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertGame", ReplyAction="http://tempuri.org/IServiceBase/InsertGameResponse")]
        int InsertGame(WpfClient.APLService.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertGame", ReplyAction="http://tempuri.org/IServiceBase/InsertGameResponse")]
        System.Threading.Tasks.Task<int> InsertGameAsync(WpfClient.APLService.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertGroup", ReplyAction="http://tempuri.org/IServiceBase/InsertGroupResponse")]
        int InsertGroup(WpfClient.APLService.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertGroup", ReplyAction="http://tempuri.org/IServiceBase/InsertGroupResponse")]
        System.Threading.Tasks.Task<int> InsertGroupAsync(WpfClient.APLService.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertGuess", ReplyAction="http://tempuri.org/IServiceBase/InsertGuessResponse")]
        int InsertGuess(WpfClient.APLService.Guess guess);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertGuess", ReplyAction="http://tempuri.org/IServiceBase/InsertGuessResponse")]
        System.Threading.Tasks.Task<int> InsertGuessAsync(WpfClient.APLService.Guess guess);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertPlayer", ReplyAction="http://tempuri.org/IServiceBase/InsertPlayerResponse")]
        int InsertPlayer(WpfClient.APLService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertPlayer", ReplyAction="http://tempuri.org/IServiceBase/InsertPlayerResponse")]
        System.Threading.Tasks.Task<int> InsertPlayerAsync(WpfClient.APLService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateUser", ReplyAction="http://tempuri.org/IServiceBase/UpdateUserResponse")]
        int UpdateUser(WpfClient.APLService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateUser", ReplyAction="http://tempuri.org/IServiceBase/UpdateUserResponse")]
        System.Threading.Tasks.Task<int> UpdateUserAsync(WpfClient.APLService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateGame", ReplyAction="http://tempuri.org/IServiceBase/UpdateGameResponse")]
        int UpdateGame(WpfClient.APLService.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateGame", ReplyAction="http://tempuri.org/IServiceBase/UpdateGameResponse")]
        System.Threading.Tasks.Task<int> UpdateGameAsync(WpfClient.APLService.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateGroup", ReplyAction="http://tempuri.org/IServiceBase/UpdateGroupResponse")]
        int UpdateGroup(WpfClient.APLService.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateGroup", ReplyAction="http://tempuri.org/IServiceBase/UpdateGroupResponse")]
        System.Threading.Tasks.Task<int> UpdateGroupAsync(WpfClient.APLService.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateGuess", ReplyAction="http://tempuri.org/IServiceBase/UpdateGuessResponse")]
        int UpdateGuess(WpfClient.APLService.Guess guess);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateGuess", ReplyAction="http://tempuri.org/IServiceBase/UpdateGuessResponse")]
        System.Threading.Tasks.Task<int> UpdateGuessAsync(WpfClient.APLService.Guess guess);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdatePlayer", ReplyAction="http://tempuri.org/IServiceBase/UpdatePlayerResponse")]
        int UpdatePlayer(WpfClient.APLService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdatePlayer", ReplyAction="http://tempuri.org/IServiceBase/UpdatePlayerResponse")]
        System.Threading.Tasks.Task<int> UpdatePlayerAsync(WpfClient.APLService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteUser", ReplyAction="http://tempuri.org/IServiceBase/DeleteUserResponse")]
        int DeleteUser(WpfClient.APLService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteUser", ReplyAction="http://tempuri.org/IServiceBase/DeleteUserResponse")]
        System.Threading.Tasks.Task<int> DeleteUserAsync(WpfClient.APLService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteGame", ReplyAction="http://tempuri.org/IServiceBase/DeleteGameResponse")]
        int DeleteGame(WpfClient.APLService.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteGame", ReplyAction="http://tempuri.org/IServiceBase/DeleteGameResponse")]
        System.Threading.Tasks.Task<int> DeleteGameAsync(WpfClient.APLService.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteGroup", ReplyAction="http://tempuri.org/IServiceBase/DeleteGroupResponse")]
        int DeleteGroup(WpfClient.APLService.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteGroup", ReplyAction="http://tempuri.org/IServiceBase/DeleteGroupResponse")]
        System.Threading.Tasks.Task<int> DeleteGroupAsync(WpfClient.APLService.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteGuess", ReplyAction="http://tempuri.org/IServiceBase/DeleteGuessResponse")]
        int DeleteGuess(WpfClient.APLService.Guess guess);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteGuess", ReplyAction="http://tempuri.org/IServiceBase/DeleteGuessResponse")]
        System.Threading.Tasks.Task<int> DeleteGuessAsync(WpfClient.APLService.Guess guess);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeletePlayer", ReplyAction="http://tempuri.org/IServiceBase/DeletePlayerResponse")]
        int DeletePlayer(WpfClient.APLService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeletePlayer", ReplyAction="http://tempuri.org/IServiceBase/DeletePlayerResponse")]
        System.Threading.Tasks.Task<int> DeletePlayerAsync(WpfClient.APLService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/Login", ReplyAction="http://tempuri.org/IServiceBase/LoginResponse")]
        WpfClient.APLService.User Login(WpfClient.APLService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/Login", ReplyAction="http://tempuri.org/IServiceBase/LoginResponse")]
        System.Threading.Tasks.Task<WpfClient.APLService.User> LoginAsync(WpfClient.APLService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetGameResults", ReplyAction="http://tempuri.org/IServiceBase/GetGameResultsResponse")]
        WpfClient.APLService.GameList GetGameResults();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetGameResults", ReplyAction="http://tempuri.org/IServiceBase/GetGameResultsResponse")]
        System.Threading.Tasks.Task<WpfClient.APLService.GameList> GetGameResultsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertNewGames", ReplyAction="http://tempuri.org/IServiceBase/InsertNewGamesResponse")]
        void InsertNewGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertNewGames", ReplyAction="http://tempuri.org/IServiceBase/InsertNewGamesResponse")]
        System.Threading.Tasks.Task InsertNewGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/LoadResults", ReplyAction="http://tempuri.org/IServiceBase/LoadResultsResponse")]
        void LoadResults();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/LoadResults", ReplyAction="http://tempuri.org/IServiceBase/LoadResultsResponse")]
        System.Threading.Tasks.Task LoadResultsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBaseChannel : WpfClient.APLService.IServiceBase, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBaseClient : System.ServiceModel.ClientBase<WpfClient.APLService.IServiceBase>, WpfClient.APLService.IServiceBase {
        
        public ServiceBaseClient() {
        }
        
        public ServiceBaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WpfClient.APLService.UserList GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<WpfClient.APLService.UserList> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public WpfClient.APLService.GameList GetAllGames() {
            return base.Channel.GetAllGames();
        }
        
        public System.Threading.Tasks.Task<WpfClient.APLService.GameList> GetAllGamesAsync() {
            return base.Channel.GetAllGamesAsync();
        }
        
        public WpfClient.APLService.GroupList GetAllGroups() {
            return base.Channel.GetAllGroups();
        }
        
        public System.Threading.Tasks.Task<WpfClient.APLService.GroupList> GetAllGroupsAsync() {
            return base.Channel.GetAllGroupsAsync();
        }
        
        public WpfClient.APLService.GuessList GetAllGuesses() {
            return base.Channel.GetAllGuesses();
        }
        
        public System.Threading.Tasks.Task<WpfClient.APLService.GuessList> GetAllGuessesAsync() {
            return base.Channel.GetAllGuessesAsync();
        }
        
        public WpfClient.APLService.PlayerList GetAllPlayers() {
            return base.Channel.GetAllPlayers();
        }
        
        public System.Threading.Tasks.Task<WpfClient.APLService.PlayerList> GetAllPlayersAsync() {
            return base.Channel.GetAllPlayersAsync();
        }
        
        public int InsertUser(WpfClient.APLService.User user) {
            return base.Channel.InsertUser(user);
        }
        
        public System.Threading.Tasks.Task<int> InsertUserAsync(WpfClient.APLService.User user) {
            return base.Channel.InsertUserAsync(user);
        }
        
        public int InsertGame(WpfClient.APLService.Game game) {
            return base.Channel.InsertGame(game);
        }
        
        public System.Threading.Tasks.Task<int> InsertGameAsync(WpfClient.APLService.Game game) {
            return base.Channel.InsertGameAsync(game);
        }
        
        public int InsertGroup(WpfClient.APLService.Group group) {
            return base.Channel.InsertGroup(group);
        }
        
        public System.Threading.Tasks.Task<int> InsertGroupAsync(WpfClient.APLService.Group group) {
            return base.Channel.InsertGroupAsync(group);
        }
        
        public int InsertGuess(WpfClient.APLService.Guess guess) {
            return base.Channel.InsertGuess(guess);
        }
        
        public System.Threading.Tasks.Task<int> InsertGuessAsync(WpfClient.APLService.Guess guess) {
            return base.Channel.InsertGuessAsync(guess);
        }
        
        public int InsertPlayer(WpfClient.APLService.Player player) {
            return base.Channel.InsertPlayer(player);
        }
        
        public System.Threading.Tasks.Task<int> InsertPlayerAsync(WpfClient.APLService.Player player) {
            return base.Channel.InsertPlayerAsync(player);
        }
        
        public int UpdateUser(WpfClient.APLService.User user) {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task<int> UpdateUserAsync(WpfClient.APLService.User user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public int UpdateGame(WpfClient.APLService.Game game) {
            return base.Channel.UpdateGame(game);
        }
        
        public System.Threading.Tasks.Task<int> UpdateGameAsync(WpfClient.APLService.Game game) {
            return base.Channel.UpdateGameAsync(game);
        }
        
        public int UpdateGroup(WpfClient.APLService.Group group) {
            return base.Channel.UpdateGroup(group);
        }
        
        public System.Threading.Tasks.Task<int> UpdateGroupAsync(WpfClient.APLService.Group group) {
            return base.Channel.UpdateGroupAsync(group);
        }
        
        public int UpdateGuess(WpfClient.APLService.Guess guess) {
            return base.Channel.UpdateGuess(guess);
        }
        
        public System.Threading.Tasks.Task<int> UpdateGuessAsync(WpfClient.APLService.Guess guess) {
            return base.Channel.UpdateGuessAsync(guess);
        }
        
        public int UpdatePlayer(WpfClient.APLService.Player player) {
            return base.Channel.UpdatePlayer(player);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePlayerAsync(WpfClient.APLService.Player player) {
            return base.Channel.UpdatePlayerAsync(player);
        }
        
        public int DeleteUser(WpfClient.APLService.User user) {
            return base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task<int> DeleteUserAsync(WpfClient.APLService.User user) {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public int DeleteGame(WpfClient.APLService.Game game) {
            return base.Channel.DeleteGame(game);
        }
        
        public System.Threading.Tasks.Task<int> DeleteGameAsync(WpfClient.APLService.Game game) {
            return base.Channel.DeleteGameAsync(game);
        }
        
        public int DeleteGroup(WpfClient.APLService.Group group) {
            return base.Channel.DeleteGroup(group);
        }
        
        public System.Threading.Tasks.Task<int> DeleteGroupAsync(WpfClient.APLService.Group group) {
            return base.Channel.DeleteGroupAsync(group);
        }
        
        public int DeleteGuess(WpfClient.APLService.Guess guess) {
            return base.Channel.DeleteGuess(guess);
        }
        
        public System.Threading.Tasks.Task<int> DeleteGuessAsync(WpfClient.APLService.Guess guess) {
            return base.Channel.DeleteGuessAsync(guess);
        }
        
        public int DeletePlayer(WpfClient.APLService.Player player) {
            return base.Channel.DeletePlayer(player);
        }
        
        public System.Threading.Tasks.Task<int> DeletePlayerAsync(WpfClient.APLService.Player player) {
            return base.Channel.DeletePlayerAsync(player);
        }
        
        public WpfClient.APLService.User Login(WpfClient.APLService.User user) {
            return base.Channel.Login(user);
        }
        
        public System.Threading.Tasks.Task<WpfClient.APLService.User> LoginAsync(WpfClient.APLService.User user) {
            return base.Channel.LoginAsync(user);
        }
        
        public WpfClient.APLService.GameList GetGameResults() {
            return base.Channel.GetGameResults();
        }
        
        public System.Threading.Tasks.Task<WpfClient.APLService.GameList> GetGameResultsAsync() {
            return base.Channel.GetGameResultsAsync();
        }
        
        public void InsertNewGames() {
            base.Channel.InsertNewGames();
        }
        
        public System.Threading.Tasks.Task InsertNewGamesAsync() {
            return base.Channel.InsertNewGamesAsync();
        }
        
        public void LoadResults() {
            base.Channel.LoadResults();
        }
        
        public System.Threading.Tasks.Task LoadResultsAsync() {
            return base.Channel.LoadResultsAsync();
        }
    }
}
